services:
  wiki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'


  wiki-api:
    container_name: wiki-api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      .env

  postgres:
    image: postgres:18
    container_name: wiki-database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-wiki}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-wiki}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiki -d wiki"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
